format = "  $all"
right_format = "$time"
add_newline = false

[directory]
style= "fg:#7aa2f7"
truncation_length = 2
truncate_to_repo = true
fish_style_pwd_dir_length = 1

[directory.substitutions]
"Documents" = " 󰧮 "
"Music" = "  "
"Movies" = " 󰿏 "
"Pictures" =  " "
"Sources" = "  "
"Downloads" = "  "
"~" = "  "
"/" = "  "

[line_break]
disabled = true

[character]
success_symbol = " [󰁔](fg:#7aa2f7) "
error_symbol =   " [ ](fg:#f7768e)[ ](fg:#f7768e) "
format = "$symbol"
disabled = false

[git_branch]
disabled = false
symbol = " "
style = "fg:#bb9af7"
truncation_length = 5
format = '[$symbol$branch(:$remote_branch)]($style) '

[git_commit]
disabled = false
commit_hash_length = 1

[git_state]
disabled = false
rebase = "rebasing"
merge = "merging"
revert = "reverting"
cherry_pick = " picking"
bisect = "bisecting"
am = "am'ing"
am_or_rebase = "am/rebase"

[git_status]
disabled = false
style= "fg:#9ece6a"
stashed = " ${count} "
ahead = "󰞙 ${count} "
behind = "󰞒 ${count} "
diverged = "󰵉 ${ahead_count} ${behind_count} "
conflicted = " ${count} "
deleted = " ${count} "
renamed = " ${count} "
modified = " ${count} "
staged = " ${count} "
untracked = "󱅘 ${count}"

[java]
disabled = false
symbol = "•  "
format = '[${symbol}]($style)'
style = "fg:#7dcfff"

[python]
disabled = false
pyenv_version_name= false
python_binary = 'python'
format = '[${symbol}(\($virtualenv\))]($style)'
style = "fg:#ff9e64"
symbol = "• 󱔎 "

[lua]
disabled = false
symbol = "• "
format = '[${symbol}]($style)'
style = "fg:#7dcfff"

[nodejs]
disabled = false
symbol = "• 󰎙 "
format = '[${symbol}]($style)'
style = "fg:#ff9e64"

[package]
disabled = false
symbol = "•  "
display_private = false
format = '[${symbol}]($style)'
style = "fg:#7dcfff"

[docker_context]
disabled = false
symbol = "•  "
only_with_files = true
format = '[${symbol}]($style)'
style = "fg:#ff9e64"

[golang]
disabled = false
symbol = "•  "
format = '[${symbol}]($style)'
style = "fg:#7dcfff"
